---
c2960s-universalk9-tar.152-2.E9.tar:
    md5: 66f500dc7da233da4c01f1856363cc2d
    models:
        - WS-C2960S-48TS-L

c2960x-universalk9-tar.152-4.E8.tar:
    md5: e0207f1709cf04f3461b012bf4fdd04f
    models:
        - WS-C2960X-48TS-L
        - WS-C2960X-48FPD-L

c3550-ipbasek9-mz.122-44.SE6.bin:
    md5: da9f2282b564b0f14259571cabb75b81
    models:
        - WS-C3550-48-SMI
        - WS-C3550-48

c3560-ipbasek9-tar.122-55.SE12.tar:
    md5: 549c9b96cb5a914f3f8a0a601f9a12c1
    models:
        - WS-C3560-24PS
        - WS-C3560-24TS
        - WS-C3560-48PS
        - WS-C3560-48TS
        - WS-C3560G-24PS
        - WS-C3560G-24TS
        - WS-C3560G-48PS
        - WS-C3560G-48TS
        
c3560e-universalk9-tar.152-4.E8.tar:
    md5: 8b50d2f228fdfbcdccae147bd720be52
    models:
        - WS-C3560X-24P
        - WS-C3560X-24T
        - WS-C3560X-48P
        - WS-C3560X-48T
        - WS-C3560X-48
        - WS-C3560X-24
        
c3750-ipbaselmk9-tar.122-55.SE12.tar:
    md5: 36e116cbbcab222d28d60f65f08b126e
    models:
        - WS-C3750G-12S
        - WS-C3750G-24PS

c3750e-universalk9-tar.152-4.E8.tar:
    md5: 4af8dc925ef1d2ba68705f9efdeae1ea
    models:
        - WS-C3750X-12S

cat3k_caa-universalk9.16.03.08.SPA.bin:
    md5: c98d0b937945f30b3cd8f58702461b6f
    models:
        - WS-C3650-48FQ
        - WS-C3650-48PQ
        - WS-C3650-48PD  
        - WS-C3650-48PD
        - WS-C3850-12S 
        - WS-C3850-24P 
        - WS-C3850-24XS
        - WS-C3850-48P
        
c2900-universalk9-mz.SPA.157-3.M4b.bin:
    md5: 15893d988e2999f5c96741c843492a1e
    models:
        - CISCO2921/K9
        
c800-universalk9-mz.SPA.156-3.M6a.bin:
    md5: 94c8b56da7456124f817b61fa02974a5
    models:
        - C892FSP-K9

# Not yet supported
nxos.7.0.3.I7.6.bin:
    md5: aea740774c1ef22585ac40f1134d3ed6
    models:
        - N9K-C93180YC-EX
        - N3K-C3064TQ-10GT

# Not yet supported        
isr4300-universalk9.16.09.03.SPA.bin:
    md5: 5553887dfc0633940a6004b78de0f9b9
    models:
        - ISR4331/K9
